import type { HistoryEntry } from '../history.js';
import { summarizeTrend } from '../history.js';

/**
 * Portfolio dashboard — one page across every tracked codebase and skill.
 *
 * Deliberately READ-ONLY and generated from result files. Evaluations keep
 * running locally against the client's machine and their Codex subscription;
 * only the scores travel. No source code, no API keys, nothing to upload —
 * which is what makes this safe to host for an agency whose clients' code is
 * confidential (and which keeps evaluation cost at zero).
 *
 * Form: small multiples. One sparkline per subject rather than many series on
 * shared axes — it scales past a handful of clients, needs no multi-hue palette
 * to decode, and each row stays independently readable. Status is a labelled
 * pill (never color alone), and the table itself is the accessible data view.
 */

export interface TrackedSubject {
  /** Where the history came from — shown so a stale entry is traceable. */
  source: string;
  entries: HistoryEntry[];
  /** Link to that subject's full report, when one is reachable (serve mode). */
  reportHref?: string;
}

export interface DashboardData {
  subjects: TrackedSubject[];
  generatedAt: string;
}

export function renderDashboard(data: DashboardData): string {
  const rows = data.subjects
    .map(toRow)
    .filter((r): r is Row => r !== null)
    .sort((a, b) => b.uplift - a.uplift);

  const clearing = rows.filter((r) => r.gatePass).length;
  const threshold = rows[0]?.threshold ?? 0.4;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>2bench portfolio</title>
<style>${STYLE}</style>
</head>
<body>
<main class="wrap">
  <header class="masthead">
    <div class="brand"><span class="mark">2bench</span><span class="tag">portfolio</span></div>
    <div class="meta">${rows.length} tracked · generated ${esc(data.generatedAt.slice(0, 10))}</div>
  </header>

  ${rows.length === 0 ? empty() : `
  <section class="tiles">
    ${tile(String(rows.length), rows.length === 1 ? 'subject tracked' : 'subjects tracked')}
    ${tile(`${clearing}/${rows.length}`, `clearing the ${pct(threshold)} bar`, clearing > 0 ? 'good' : 'warn')}
    ${tile(signed(median(rows.map((r) => r.uplift))), 'median uplift')}
    ${tile(String(rows.reduce((s, r) => s + r.runs, 0)), 'runs recorded')}
  </section>

  <section class="panel">
    <div class="table-scroll">
    <table>
      <thead><tr>
        <th>Subject</th><th>Kind</th><th class="num">Uplift</th><th class="num">95% CI</th>
        <th>Trend</th><th class="num">Runs</th><th>Last run</th><th>Status</th>
      </tr></thead>
      <tbody>
        ${rows.map(renderRow).join('\n')}
      </tbody>
    </table>
    </div>
    <p class="note">Uplift is the latest run's headline: how much better the subject scored than a zero-shot LLM given the same information. Status uses the <em>lower bound</em> of the confidence interval, never the point estimate — a wide interval on few samples will not certify a claim.</p>
  </section>

  ${staleNote(rows)}
  `}

  <footer class="foot">
    Generated by 2bench from local result files. Evaluations run on the machine that owns the code — only scores are collected here.
  </footer>
</main>
</body>
</html>`;
}

interface Row {
  name: string;
  kind: 'codebase' | 'skill';
  uplift: number;
  lo: number;
  hi: number;
  gatePass: boolean;
  threshold: number;
  runs: number;
  at: string;
  series: number[];
  delta: number | null;
  baselineChanged: boolean;
  warnings: number;
  href?: string;
}

function toRow(subject: TrackedSubject): Row | null {
  const trend = summarizeTrend(subject.entries);
  if (!trend) return null;
  const e = trend.latest;
  return {
    name: e.subjectName || e.repoRoot,
    kind: e.subjectKind ?? 'codebase',
    uplift: e.uplift,
    lo: e.upliftLo,
    hi: e.upliftHi,
    gatePass: e.gatePass,
    threshold: e.gateThreshold,
    runs: trend.runs,
    at: e.at,
    series: subject.entries.map((x) => x.uplift),
    delta: trend.deltaFromPrevious,
    baselineChanged: trend.baselineChanged,
    warnings: e.warnings ?? 0,
    href: subject.reportHref,
  };
}

function renderRow(r: Row): string {
  const dir = r.delta === null ? '' : r.delta > 0.01 ? 'up' : r.delta < -0.01 ? 'down' : 'flat';
  const deltaCell =
    r.delta === null
      ? '<span class="muted-text">first run</span>'
      : `<span class="delta ${dir}">${dir === 'up' ? '▲' : dir === 'down' ? '▼' : '→'} ${signed(r.delta)}</span>`;
  return `<tr>
    <td class="subject">${r.href ? `<a href="${esc(r.href)}">${esc(r.name)}</a>` : esc(r.name)}${r.warnings > 0 ? `<span class="caveat" title="${r.warnings} measurement caveat(s) on the latest run">⚠ ${r.warnings}</span>` : ''}</td>
    <td><span class="kind ${r.kind}">${r.kind}</span></td>
    <td class="num strong">${signed(r.uplift)}</td>
    <td class="num small">${signed(r.lo)} – ${signed(r.hi)}</td>
    <td class="trendcell">${sparkline(r.series)}<div class="delta-wrap">${deltaCell}${r.baselineChanged ? '<span class="caveat" title="Baseline model changed since the previous run — this move reflects LLM capability, not only the pipeline">model↑</span>' : ''}</div></td>
    <td class="num">${r.runs}</td>
    <td class="small">${esc(r.at.slice(0, 10))}</td>
    <td><span class="pill ${r.gatePass ? 'pass' : 'below'}">${r.gatePass ? '✓ clears' : '• below'}</span></td>
  </tr>`;
}

/**
 * Sparkline: no axes, a zero rule (uplift can be negative), emphasized endpoint.
 * A single accent hue — identity comes from the row, not from color.
 */
export function sparkline(values: readonly number[], w = 132, h = 30): string {
  if (values.length === 0) return '';
  if (values.length === 1) {
    return `<svg class="spark" viewBox="0 0 ${w} ${h}" role="img" aria-label="single run, no trend yet"><circle cx="${w / 2}" cy="${h / 2}" r="3" class="end"/></svg>`;
  }
  const lo = Math.min(...values, 0);
  const hi = Math.max(...values, 0);
  const span = hi - lo || 1;
  const pad = 4;
  const x = (i: number) => pad + (i / (values.length - 1)) * (w - pad * 2);
  const y = (v: number) => pad + (1 - (v - lo) / span) * (h - pad * 2);
  const path = values.map((v, i) => `${i === 0 ? 'M' : 'L'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');
  const zeroY = y(0).toFixed(1);
  const lastI = values.length - 1;
  return `<svg class="spark" viewBox="0 0 ${w} ${h}" role="img" aria-label="uplift across ${values.length} runs, latest ${signed(values[lastI]!)}">
    <line class="zero" x1="0" y1="${zeroY}" x2="${w}" y2="${zeroY}"/>
    <path class="line" d="${path}"/>
    <circle class="end" cx="${x(lastI).toFixed(1)}" cy="${y(values[lastI]!).toFixed(1)}" r="3"/>
  </svg>`;
}

function tile(value: string, label: string, tone = ''): string {
  return `<div class="tile ${tone}"><div class="tile-num">${esc(value)}</div><div class="tile-label">${esc(label)}</div></div>`;
}

function staleNote(rows: readonly Row[]): string {
  const single = rows.filter((r) => r.runs === 1).length;
  if (single === 0) return '';
  return `<p class="note standalone">${single} subject${single === 1 ? ' has' : 's have'} only one recorded run — no trend yet. Re-run periodically: the vanilla-LLM baseline improves over time, so a score is a snapshot, not a standing claim.</p>`;
}

function empty(): string {
  return `<section class="panel empty">
    <h2>No results yet</h2>
    <p class="note">Point this at directories containing <code>history.jsonl</code> — each one is produced by <code>2bench score</code> or <code>2bench skill</code>.</p>
  </section>`;
}

function median(xs: readonly number[]): number {
  if (xs.length === 0) return 0;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid]! : (s[mid - 1]! + s[mid]!) / 2;
}

function pct(x: number): string {
  return `${Math.round(x * 100)}%`;
}
function signed(x: number): string {
  return `${x >= 0 ? '+' : '−'}${Math.abs(Math.round(x * 100))}%`;
}
function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

const STYLE = `
:root{
  --ground:#f7f9fb; --surface:#fff; --ink:#16212c; --muted:#5b6b7a; --hairline:#e2e8ef;
  --accent:#2e5aac; --chart:#2e5aac; --good:#1c7a48; --good-soft:#d8efe1;
  --warn:#a9741a; --warn-soft:#f7ecd8; --bad:#b4401a;
  --radius:12px; --shadow:0 1px 2px rgba(16,33,48,.06),0 6px 24px rgba(16,33,48,.05);
  --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
}
@media (prefers-color-scheme:dark){:root{
  --ground:#0e141b; --surface:#161f29; --ink:#e7edf3; --muted:#93a2b1; --hairline:#26313d;
  --accent:#6e93f2; --chart:#6389ee; --good:#3ec981; --good-soft:#12291d;
  --warn:#e0a93b; --warn-soft:#2a2114; --bad:#f2795b;
  --shadow:0 1px 2px rgba(0,0,0,.3),0 8px 30px rgba(0,0,0,.35);
}}
:root[data-theme="light"]{--ground:#f7f9fb;--surface:#fff;--ink:#16212c;--muted:#5b6b7a;--hairline:#e2e8ef;--accent:#2e5aac;--chart:#2e5aac;--good:#1c7a48;--good-soft:#d8efe1;--warn:#a9741a;--warn-soft:#f7ecd8;--bad:#b4401a;}
:root[data-theme="dark"]{--ground:#0e141b;--surface:#161f29;--ink:#e7edf3;--muted:#93a2b1;--hairline:#26313d;--accent:#6e93f2;--chart:#6389ee;--good:#3ec981;--good-soft:#12291d;--warn:#e0a93b;--warn-soft:#2a2114;--bad:#f2795b;}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);line-height:1.55;-webkit-font-smoothing:antialiased}
.wrap{max-width:1000px;margin:0 auto;padding:32px 24px 64px}
.masthead{display:flex;justify-content:space-between;align-items:baseline;flex-wrap:wrap;gap:8px;padding-bottom:20px;border-bottom:1px solid var(--hairline)}
.brand{display:flex;align-items:baseline;gap:10px}
.mark{font-weight:700;font-size:1.3rem;letter-spacing:-.02em}
.tag{color:var(--muted);font-size:.85rem}
.meta{font-family:var(--mono);font-size:.8rem;color:var(--muted)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin:24px 0}
.tile{padding:16px 18px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);box-shadow:var(--shadow)}
.tile.good{border-left:4px solid var(--good)}
.tile.warn{border-left:4px solid var(--warn)}
.tile-num{font-family:var(--mono);font-size:1.7rem;font-weight:700;letter-spacing:-.02em;font-variant-numeric:tabular-nums}
.tile-label{font-size:.8rem;color:var(--muted);margin-top:2px}
.panel{margin:24px 0;padding:18px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);box-shadow:var(--shadow)}
.panel.empty{text-align:center;padding:48px 18px}
.table-scroll{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:.87rem;min-width:760px}
th{text-align:left;font-weight:600;font-size:.76rem;letter-spacing:.03em;text-transform:uppercase;color:var(--muted);border-bottom:1px solid var(--hairline);padding:0 14px 8px 0;white-space:nowrap}
td{padding:12px 14px 12px 0;border-bottom:1px solid var(--hairline);vertical-align:middle}
tr:last-child td{border-bottom:none}
.num{font-family:var(--mono);font-variant-numeric:tabular-nums;text-align:right}
th.num{text-align:right}
.strong{font-weight:700;font-size:1rem}
.small{font-size:.78rem;color:var(--muted)}
.subject{font-weight:600;max-width:230px}
.subject a{color:var(--accent);text-decoration:none}
.subject a:hover{text-decoration:underline}
.subject a:focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:3px}
.caveat{display:inline-block;margin-left:6px;font-size:.7rem;font-family:var(--mono);color:var(--warn);background:var(--warn-soft);border-radius:5px;padding:1px 5px;vertical-align:middle}
.kind{font-size:.72rem;font-family:var(--mono);border:1px solid var(--hairline);border-radius:5px;padding:2px 7px;color:var(--muted)}
.kind.skill{border-color:var(--accent);color:var(--accent)}
.trendcell{min-width:150px}
.spark{width:132px;height:30px;display:block}
.spark .line{fill:none;stroke:var(--chart);stroke-width:2;stroke-linejoin:round;stroke-linecap:round}
.spark .zero{stroke:var(--hairline);stroke-width:1}
.spark .end{fill:var(--chart)}
.delta-wrap{display:flex;align-items:center;gap:6px;margin-top:2px}
.delta{font-family:var(--mono);font-size:.74rem}
.delta.up{color:var(--good)}
.delta.down{color:var(--bad)}
.delta.flat,.muted-text{color:var(--muted);font-size:.74rem;font-family:var(--mono)}
.pill{display:inline-block;font-size:.75rem;font-weight:600;border-radius:20px;padding:3px 10px;white-space:nowrap}
.pill.pass{background:var(--good-soft);color:var(--good)}
.pill.below{background:var(--warn-soft);color:var(--warn)}
.note{font-size:.8rem;color:var(--muted);margin:14px 0 0;max-width:70ch}
.note.standalone{margin:18px 0 0;padding:12px 14px;background:var(--surface);border:1px solid var(--hairline);border-left:3px solid var(--warn);border-radius:8px}
code{font-family:var(--mono);font-size:.9em;background:var(--ground);border:1px solid var(--hairline);border-radius:4px;padding:1px 5px}
.foot{margin-top:32px;padding-top:16px;border-top:1px solid var(--hairline);font-size:.78rem;color:var(--muted);text-align:center;max-width:70ch;margin-left:auto;margin-right:auto}
`;
