import type { Dimension, DimensionResult, PairOutcome, RunResult } from '../types.js';
import type { HistoryEntry } from '../history.js';
import { TREND_STYLE, renderTrendChart } from './trend-chart.js';

/**
 * Client-facing report — a single self-contained HTML file (no external assets,
 * works offline). Audience: an SMB owner plus their technical advisor, so the
 * verdict reads at a glance and the methodology is one scroll away and honest.
 *
 * Design: instrument-panel. Cool-neutral palette, steel-blue accent; semantic
 * pass/warn/fail colors are separate from the accent and always paired with a
 * text label + glyph (never color alone). Both light/dark themes via tokens.
 */

const DIMENSION_LABEL: Record<Dimension, string> = {
  correctness: 'Correctness & tests',
  security: 'Security & compliance',
  maintainability: 'Maintainability',
  consistency: 'Consistency & determinism',
};

const DIMENSION_BLURB: Record<Dimension, string> = {
  correctness: 'Does it work — behavior against the spec, edge cases, tests.',
  security: 'Injection/XSS resistance, no hardcoded secrets, safe error handling.',
  maintainability: 'Modularity, low duplication, manageable complexity.',
  consistency: 'A shipped, fixed artifact vs. code that changes every regeneration.',
};

export function renderHtmlReport(result: RunResult, history: readonly HistoryEntry[] = []): string {
  const { headline, dimensions, meta } = result;
  const tally = tallyOutcomes(result.outcomes);
  const hasComparison = result.outcomes.length > 0 || dimensions.some((d) => d.inUplift);
  const extracted = meta.specSource !== 'linear';
  const isSkill = meta.subject?.kind === 'skill';
  const L = isSkill
    ? { treatment: 'With this skill', control: 'Plain prompting', unit: 'tasks', tagline: 'skill vs. plain prompting' }
    : { treatment: 'This codebase', control: 'Pure-LLM baseline', unit: 'modules', tagline: 'codebase vs. pure-LLM baseline' };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>2bench report — ${esc(shortRepo(meta.repoRoot))}</title>
<style>${STYLE}${TREND_STYLE}</style>
</head>
<body>
<main class="wrap">
  <header class="masthead">
    <div class="brand"><span class="mark">2bench</span><span class="tag">${L.tagline}</span></div>
    <div class="repo">${esc(isSkill ? meta.repoRoot : shortRepo(meta.repoRoot))}</div>
  </header>

  ${hasComparison ? verdictBand(headline, tally) : healthNotice()}

  <section class="panel">
    <h2>By dimension</h2>
    <p class="lead">${
      isSkill
        ? 'How the skill’s output compares to the same model prompted without it, on the same tasks. Bars show each side’s score; “uplift” is the relative improvement.'
        : 'How the delivered code compares to a zero-shot LLM regeneration of the same specs, per quality dimension. Bars show each side’s score; “uplift” is the relative improvement.'
    }</p>
    <div class="dims">
      ${dimensions.map((d) => dimensionRow(d, L)).join('\n')}
    </div>
    <p class="weights">Headline weighting — ${dimensions.map((d) => `${DIMENSION_LABEL[d.dimension].split(' ')[0]} ${(d.weight * 100).toFixed(0)}%`).join(' · ')}. Weights are configurable and always disclosed.</p>
  </section>

  ${renderTrendChart(history)}

  ${meta.warnings.length > 0 ? warningsPanel(meta.warnings) : ''}

  ${contextBand()}

  <details class="method">
    <summary>Methodology &amp; limitations</summary>
    <div class="method-body">
      <ul>
        <li><strong>Sample.</strong> ${meta.modulesSampled} of ${meta.modulesTotal} ${L.unit}${isSkill ? '' : ', stratified by subsystem'}, seed ${meta.seed} (reproducible).</li>
        <li><strong>Comparison.</strong> ${
          isSkill
            ? `Every task was run twice through the same model (${esc(meta.baselineModel)}) — once with the skill, once without — ${meta.samplesPerSpec} samples per arm. The skill text is the only difference between the arms.`
            : `Each sampled module's spec was regenerated by a vanilla LLM (${esc(meta.baselineModel)}) with no project context or custom skills — ${meta.samplesPerSpec} samples per spec.`
        }</li>
        ${
          isSkill
            ? '<li><strong>Task source.</strong> The benchmark\'s own task prompts — identical for both arms, so there is no spec-derivation bias.</li>'
            : `<li><strong>Spec source.</strong> ${esc(meta.specSource)}.${extracted ? ' <em>Specs were extracted from the code rather than taken from original tickets — a known validity caveat (a spec derived from good code can flatter the baseline). Treat as a lower bound.</em>' : ''}</li>`
        }
        <li><strong>Head-to-head decisions.</strong> ${tally.total} comparisons — ${tally.repo} to the codebase, ${tally.baseline} to the baseline, ${tally.tie} ties. Deterministic where a tool could decide it; otherwise an LLM judge run <em>twice with the two implementations swapped</em>, with disagreement counted as a tie (position-bias control).</li>
        <li><strong>Statistics.</strong> Win rate uses a Wilson interval; uplift uses a paired per-module bootstrap. The gate passes only if the interval's <em>lower</em> bound clears the threshold — never the point estimate.</li>
        <li><strong>Known limitations.</strong> Small samples widen intervals; a single-family judge that generated the baseline is biased toward the baseline (so measured uplift is conservative); dimensions without a deterministic signal rely on the judge.</li>
      </ul>
      <div class="tools">${Object.entries(meta.toolVersions).map(([k, v]) => `<span>${esc(k)} ${esc(v)}</span>`).join('')}</div>
    </div>
  </details>

  <footer class="foot">
    Generated by 2bench · ${esc(meta.finishedAt)} · seed ${meta.seed}
  </footer>
</main>
</body>
</html>`;
}

// --- sections --------------------------------------------------------------

function verdictBand(headline: RunResult['headline'], tally: Tally): string {
  const pass = headline.gate.pass;
  const state = pass ? 'pass' : 'fail';
  const glyph = pass ? '✓' : '✕';
  const verdict = pass
    ? `Clears the ${pct(headline.gate.threshold)} bar`
    : `Below the ${pct(headline.gate.threshold)} bar`;
  return `<section class="verdict ${state}">
    <div class="badge" role="img" aria-label="${pass ? 'Pass' : 'Below threshold'}"><span class="glyph">${glyph}</span><span class="badge-text">${pass ? 'PASS' : 'REVIEW'}</span></div>
    <div class="verdict-main">
      <div class="verdict-head">${verdict}</div>
      <div class="metrics">
        <div class="metric">
          <div class="metric-num">${signed(headline.uplift.estimate)}</div>
          <div class="metric-label">overall uplift vs. pure LLM</div>
          <div class="metric-ci">95% CI ${signed(headline.uplift.lo)} – ${signed(headline.uplift.hi)}</div>
        </div>
        <div class="metric">
          <div class="metric-num">${pct(headline.winRate.estimate)}</div>
          <div class="metric-label">head-to-head checks won</div>
          <div class="metric-ci">95% CI ${pct(headline.winRate.lo)} – ${pct(headline.winRate.hi)} · n=${tally.total}</div>
        </div>
      </div>
    </div>
  </section>`;
}

function healthNotice(): string {
  return `<section class="verdict neutral">
    <div class="badge"><span class="glyph">◔</span><span class="badge-text">HEALTH</span></div>
    <div class="verdict-main">
      <div class="verdict-head">Repo-health only — no baseline comparison</div>
      <p class="lead">This run made no baseline regeneration, so there is no uplift figure. Run a full evaluation (with Codex available) to compare against a pure-LLM baseline.</p>
    </div>
  </section>`;
}

interface Labels { treatment: string; control: string; unit: string; tagline: string }

function dimensionRow(d: DimensionResult, L: Labels): string {
  if (!d.inUplift) {
    return `<div class="dim muted">
      <div class="dim-head"><span class="dim-name">${DIMENSION_LABEL[d.dimension]}</span><span class="dim-uplift na">not measured</span></div>
      <div class="dim-blurb">${DIMENSION_BLURB[d.dimension]}</div>
    </div>`;
  }
  const dir = d.uplift >= 0 ? 'up' : 'down';
  return `<div class="dim">
    <div class="dim-head">
      <span class="dim-name">${DIMENSION_LABEL[d.dimension]}</span>
      <span class="dim-uplift ${dir}">${signed(d.uplift)}<span class="arrow" aria-hidden="true">${d.uplift >= 0 ? '▲' : '▼'}</span></span>
    </div>
    <div class="dim-blurb">${DIMENSION_BLURB[d.dimension]}</div>
    <div class="bars">
      ${bar(L.treatment, d.repoScore, 'repo')}
      ${bar(L.control, d.baselineScore, 'base')}
    </div>
    <div class="dim-meta">${d.modulesMeasured} ${L.unit.replace(/s$/, '')}${d.modulesMeasured === 1 ? '' : 's'} measured</div>
  </div>`;
}

function bar(label: string, score: number | null, kind: 'repo' | 'base'): string {
  const missing = score === null || Number.isNaN(score);
  const w = missing ? 0 : Math.round(score * 100);
  return `<div class="bar-row">
    <span class="bar-label">${label}</span>
    <span class="bar-track"><span class="bar-fill ${kind}" style="width:${w}%"></span></span>
    <span class="bar-val">${missing ? 'n/a' : pct(score)}</span>
  </div>`;
}

function warningsPanel(warnings: readonly string[]): string {
  return `<section class="caveats">
    <h2>What we could not measure</h2>
    <p class="lead">Where the evidence wasn't strong enough to score a dimension, we say so rather than publish a number we can't stand behind.</p>
    <ul>${warnings.map((w) => `<li>${esc(w)}</li>`).join('')}</ul>
  </section>`;
}

function contextBand(): string {
  return `<section class="context">
    <h2>Why this comparison is meaningful</h2>
    <div class="cards">
      <div class="ctx"><div class="ctx-stat">~45%</div><p>of zero-shot LLM code carries an OWASP Top-10 security flaw — a rate flat since 2024 even as syntax quality climbed past 95%.<span class="cite">Veracode GenAI reports</span></p></div>
      <div class="ctx"><div class="ctx-stat">4×</div><p>growth in copy-pasted code blocks across large codebases from 2021–2024; 2024 was the first year copy/paste exceeded moved code.<span class="cite">GitClear, 211M lines</span></p></div>
      <div class="ctx"><div class="ctx-stat">non-det.</div><p>Identical prompts yield different code each run; a shipped, reviewed artifact does not. Consistency is a real, measurable advantage.<span class="cite">documented in the literature</span></p></div>
    </div>
  </section>`;
}

// --- helpers ---------------------------------------------------------------

interface Tally { repo: number; baseline: number; tie: number; total: number; }

function tallyOutcomes(outcomes: readonly PairOutcome[]): Tally {
  const t: Tally = { repo: 0, baseline: 0, tie: 0, total: outcomes.length };
  for (const o of outcomes) {
    if (o.winner === 'repo') t.repo++;
    else if (o.winner === 'baseline') t.baseline++;
    else t.tie++;
  }
  return t;
}

function pct(x: number): string {
  return Number.isNaN(x) ? 'n/a' : `${(x * 100).toFixed(0)}%`;
}
function signed(x: number): string {
  if (Number.isNaN(x)) return 'n/a';
  return `${x >= 0 ? '+' : '−'}${Math.abs(x * 100).toFixed(0)}%`;
}
function shortRepo(p: string): string {
  return p.split(/[\\/]/).filter(Boolean).slice(-2).join('/') || p;
}
function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

const STYLE = `
:root{
  --ground:#f7f9fb; --surface:#ffffff; --ink:#16212c; --muted:#5b6b7a;
  --hairline:#e2e8ef; --accent:#2e5aac; --accent-soft:#dbe6f7;
  --good:#1c7a48; --good-soft:#d8efe1; --warn:#a9741a; --bad:#b4401a; --bad-soft:#f6e0d6;
  --repo:#2e5aac; --base:#8a94a0;
  /* chart mark: validated against the chart lightness band per mode */
  --chart:#2e5aac;
  --shadow:0 1px 2px rgba(16,33,48,.06),0 6px 24px rgba(16,33,48,.05);
  --radius:12px;
  --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
}
@media (prefers-color-scheme:dark){:root{
  --ground:#0e141b; --surface:#161f29; --ink:#e7edf3; --muted:#93a2b1;
  --hairline:#26313d; --accent:#6e93f2; --accent-soft:#1c2a44;
  --good:#3ec981; --good-soft:#12291d; --warn:#e0a93b; --bad:#f2795b; --bad-soft:#2c1a13;
  --repo:#6e93f2; --base:#5f6b78; --chart:#6389ee;
  --shadow:0 1px 2px rgba(0,0,0,.3),0 8px 30px rgba(0,0,0,.35);
}}
:root[data-theme="light"]{--ground:#f7f9fb;--surface:#fff;--ink:#16212c;--muted:#5b6b7a;--hairline:#e2e8ef;--accent:#2e5aac;--accent-soft:#dbe6f7;--good:#1c7a48;--good-soft:#d8efe1;--warn:#a9741a;--bad:#b4401a;--bad-soft:#f6e0d6;--repo:#2e5aac;--base:#8a94a0;--chart:#2e5aac;}
:root[data-theme="dark"]{--ground:#0e141b;--surface:#161f29;--ink:#e7edf3;--muted:#93a2b1;--hairline:#26313d;--accent:#6e93f2;--accent-soft:#1c2a44;--good:#3ec981;--good-soft:#12291d;--warn:#e0a93b;--bad:#f2795b;--bad-soft:#2c1a13;--repo:#6e93f2;--base:#5f6b78;--chart:#6389ee;}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);line-height:1.55;-webkit-font-smoothing:antialiased}
.wrap{max-width:860px;margin:0 auto;padding:32px 24px 64px}
h2{font-size:1.15rem;letter-spacing:-.01em;margin:0 0 4px}
.lead{color:var(--muted);margin:.25rem 0 1rem;max-width:60ch}
.masthead{display:flex;justify-content:space-between;align-items:baseline;flex-wrap:wrap;gap:8px;padding-bottom:20px;border-bottom:1px solid var(--hairline)}
.brand{display:flex;align-items:baseline;gap:10px}
.mark{font-weight:700;font-size:1.3rem;letter-spacing:-.02em}
.tag{color:var(--muted);font-size:.85rem}
.repo{font-family:var(--mono);font-size:.85rem;color:var(--muted)}
.verdict{display:flex;gap:20px;align-items:center;margin:24px 0;padding:22px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);box-shadow:var(--shadow)}
.verdict.pass{border-left:4px solid var(--good)}
.verdict.fail{border-left:4px solid var(--warn)}
.verdict.neutral{border-left:4px solid var(--base)}
.badge{display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:88px;padding:14px;border-radius:10px;background:var(--accent-soft)}
.verdict.pass .badge{background:var(--good-soft)}
.verdict.fail .badge{background:var(--bad-soft)}
.badge .glyph{font-size:1.8rem;line-height:1}
.verdict.pass .glyph{color:var(--good)}
.verdict.fail .glyph{color:var(--bad)}
.badge-text{font-size:.72rem;font-weight:700;letter-spacing:.08em;margin-top:4px}
.verdict-main{flex:1;min-width:0}
.verdict-head{font-size:1.05rem;font-weight:600;margin-bottom:12px}
.metrics{display:flex;gap:32px;flex-wrap:wrap}
.metric-num{font-family:var(--mono);font-size:2rem;font-weight:600;letter-spacing:-.02em;font-variant-numeric:tabular-nums}
.metric-label{font-size:.82rem;color:var(--muted)}
.metric-ci{font-family:var(--mono);font-size:.75rem;color:var(--muted);margin-top:2px}
.panel,.context{margin:28px 0}
.dims{display:flex;flex-direction:column;gap:14px}
.dim{padding:16px 18px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius)}
.dim.muted{opacity:.7}
.dim-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px}
.dim-name{font-weight:600}
.dim-uplift{font-family:var(--mono);font-weight:600;font-variant-numeric:tabular-nums}
.dim-uplift.up{color:var(--good)}
.dim-uplift.down{color:var(--bad)}
.dim-uplift.na{color:var(--muted);font-weight:400;font-size:.85rem}
.arrow{font-size:.7em;margin-left:3px}
.dim-blurb{color:var(--muted);font-size:.85rem;margin:2px 0 12px}
.bars{display:flex;flex-direction:column;gap:7px}
.bar-row{display:grid;grid-template-columns:130px 1fr 42px;align-items:center;gap:10px}
.bar-label{font-size:.8rem;color:var(--muted)}
.bar-track{height:9px;background:var(--hairline);border-radius:5px;overflow:hidden}
.bar-fill{display:block;height:100%;border-radius:5px}
.bar-fill.repo{background:var(--repo)}
.bar-fill.base{background:var(--base)}
.bar-val{font-family:var(--mono);font-size:.8rem;text-align:right;font-variant-numeric:tabular-nums}
.dim-meta{font-size:.75rem;color:var(--muted);margin-top:10px}
.weights{font-size:.8rem;color:var(--muted);margin-top:14px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px}
.ctx{padding:16px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius)}
.ctx-stat{font-family:var(--mono);font-size:1.6rem;font-weight:700;color:var(--accent);letter-spacing:-.02em}
.ctx p{font-size:.85rem;margin:.4rem 0 0}
.cite{display:block;margin-top:8px;font-size:.72rem;color:var(--muted);font-style:italic}
.caveats{margin:28px 0;padding:18px;background:var(--surface);border:1px solid var(--hairline);border-left:4px solid var(--warn);border-radius:var(--radius)}
.caveats ul{margin:0;padding-left:18px}
.caveats li{font-size:.85rem;margin:6px 0}
.method{margin:28px 0;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius)}
.method summary{cursor:pointer;padding:16px 18px;font-weight:600}
.method summary:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
.method-body{padding:0 18px 18px}
.method-body ul{margin:0;padding-left:18px}
.method-body li{margin:6px 0;font-size:.88rem}
.tools{display:flex;flex-wrap:wrap;gap:6px;margin-top:14px}
.tools span{font-family:var(--mono);font-size:.72rem;color:var(--muted);background:var(--ground);border:1px solid var(--hairline);border-radius:6px;padding:2px 7px}
.foot{margin-top:32px;padding-top:16px;border-top:1px solid var(--hairline);font-size:.78rem;color:var(--muted);text-align:center}
@media (max-width:560px){.verdict{flex-direction:column;align-items:stretch}.bar-row{grid-template-columns:100px 1fr 38px}}
`;
